# executable files for this directory
OBJECTS = main_only.exe forcount.exe for_ex.exe whilecount.exe \
	  add.exe avg_price.exe \
	  item_io.exe add_item.exe add_item2.exe \
	  count.exe userforcount.exe mysum.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

