# executable files for this directory
OBJECTS = screen3.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

screen3.o: screen3.h
